
const SUPABASE_URL='https://hwyscirbycojwndyzozn.supabase.co';
const SUPABASE_ANON_KEY=window.TPL_CONFIG?.supabasePublishableKey||window.TPL_SUPABASE_ANON_KEY||document.querySelector('meta[name="tpl-supabase-anon"]')?.content||'sb_publishable_p2F_lxf_oWyjQcPq_cQw1Q_rr7E3h4k';
const pageType=document.body.dataset.marketType||'todos';
const grid=document.getElementById('market-grid');
const queryInput=document.getElementById('market-query');
const regionSelect=document.getElementById('market-region');
const searchButton=document.getElementById('market-search-btn');
const fallback=[];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function card(x){const image=x.imagen_principal_url||x.imagen_url||x.logo_url||'assets/logo-tu-parcela-lista.png';const type=x.tipo||x.tipo_oferta;const label={casa:'Casa',servicio:'Servicio',producto:'Producto',arriendo:'Arriendo',turismo:'Turismo'}[type]||'Catálogo';const price=x.precio_desde?`Desde $${Number(x.precio_desde).toLocaleString('es-CL')}`:'';return `<article class="pm-card"><img src="${esc(image)}" alt="${esc(x.titulo||x.nombre_comercial)}"><div class="pm-card-body"><div class="pm-kicker">${label}</div><h2>${esc(x.titulo||x.nombre_comercial)}</h2><p>${esc(x.resumen||x.propuesta_corta||x.descripcion_servicios||'')}</p><div class="pm-meta"><span>${esc(x.region||'Cobertura por consultar')}</span>${price?`<span>${esc(price)}</span>`:''}${x.puntaje_completitud?`<span>Perfil ${x.puntaje_completitud}%</span>`:''}</div><div class="pm-actions"><a class="pm-btn" href="${x.partner_slug?`red-partner-v2/perfil.html?slug=${encodeURIComponent(x.partner_slug)}`:`placemarket.html?item=${encodeURIComponent(x.slug||'')}`}">Ver detalle</a></div></div></article>`}
async function load(){grid.innerHTML='<div class="pm-empty">Buscando alternativas…</div>';const payload={p_tipo:pageType,p_busqueda:queryInput?.value.trim()||null,p_region:regionSelect?.value||null,p_limite:60};try{if(!SUPABASE_ANON_KEY)throw new Error('sin clave');const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/tpl_catalogo_publico_buscar_v2`,{method:'POST',headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());const data=await r.json();const items=Array.isArray(data)?data:(data?.items||[]);grid.innerHTML=items.length?items.map(card).join(''):'<div class="pm-empty">Todavía no hay publicaciones en esta categoría. Sé uno de los primeros Partners en publicar.</div>';}catch(e){console.warn(e);grid.innerHTML='<div class="pm-empty">El catálogo se conectará cuando se aplique la migración de PlaceMarket. La postulación Partner ya está disponible.</div>';}}
searchButton?.addEventListener('click',load);queryInput?.addEventListener('keydown',e=>{if(e.key==='Enter')load()});load();
