const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(n||0));
const normalize=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const works={quincho_abierto:'Quincho abierto (m²)',quincho_cerrado:'Quincho cerrado (m²)',terraza_sin_techo:'Terraza sin techo (m²)',terraza_techada:'Terraza techada (m²)',bodega_madera:'Bodega madera (m²)',bodega_solida:'Bodega sólida (m²)',galpon:'Galpón (m²)',cobertizo:'Cobertizo (m²)',estacionamiento_techado:'Estacionamiento techado (m²)',piscina_fibra:'Piscina fibra (m²)',piscina_hormigon:'Piscina hormigón (m²)',tinaja_simple:'Tinaja simple (un.)',tinaja_equipada:'Tinaja equipada (un.)',porton_automatico:'Portón automático (un.)'};
let mode='rapida',lastResult=null,lastInput=null,catalog=null;
function buildWorks(){const g=$('#worksGrid');if(!g)return;g.innerHTML='';Object.entries(works).forEach(([k,l])=>{const lab=document.createElement('label');lab.innerHTML=`<span>${l}</span><input type="number" min="0" step="1" data-work="${k}" value="0">`;g.appendChild(lab)})}
async function ensureCatalog(){
 if(globalThis.TPL_NATIONAL_CATALOG)return globalThis.TPL_NATIONAL_CATALOG;
 try{const mod=await import('./tpl-national-catalog.mjs');return mod.TPL_NATIONAL_CATALOG||globalThis.TPL_NATIONAL_CATALOG||null}catch(e){console.warn('Catálogo territorial no disponible.',e);return null}
}
async function fillRegions(){
 catalog=await ensureCatalog();const r=$('#region'),c=$('#comuna');
 if(!catalog?.regions?.length||!catalog?.communes?.length){r.innerHTML='<option value="">No fue posible cargar regiones</option>';c.innerHTML='<option value="">Catálogo no disponible</option>';return}
 r.innerHTML='<option value="">Selecciona región</option>'+catalog.regions.map(x=>`<option value="${x.name}">${x.name}</option>`).join('');
 r.onchange=()=>fillCommunes(r.value);
}
function fillCommunes(regionName){const c=$('#comuna');const reg=catalog?.regions?.find(x=>x.name===regionName);const list=(catalog?.communes||[]).filter(x=>x.reg===reg?.code).sort((a,b)=>a.name.localeCompare(b.name,'es'));c.innerHTML='<option value="">Selecciona comuna</option>'+list.map(x=>`<option value="${x.name}">${x.name}</option>`).join('');c.disabled=!regionName}
function setMode(next){mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('is-active',b.dataset.mode===next));$('#preciseFields').hidden=next!=='precisa';document.body.dataset.valuationMode=next}
function parseMoney(v){return Number(String(v||'').replace(/[^0-9]/g,''))||0}
function inputs(){
 const obras={};document.querySelectorAll('[data-work]').forEach(el=>{const n=Number(el.value||0);if(n>0)obras[el.dataset.work]=n});
 const withHouse=$('#incluyeVivienda').checked;const nature=[...document.querySelectorAll('[data-nature]:checked')].map(x=>x.value);
 const base={area:Number($('#superficie').value||0),distanceKm:Number($('#distanceKm').value||0),region:$('#region').value,comuna:$('#comuna').value,rol:$('#rol').value,electricity:$('#electricity').value,topography:$('#topography').value,water:$('#water').value,mode};
 if(mode==='precisa')Object.assign(base,{access:$('#access').value,routeDistanceKm:Number($('#routeDistanceKm').value||0),soil:$('#soil').value,exposure:$('#exposure').value,view:$('#view').value,vegetation:$('#vegetation').value,fencing:$('#fencing').value,gate:$('#gate').value,condominium:$('#condominium').value,asking:parseMoney($('#asking').value),nature,lat:Number($('#lat').value),lng:Number($('#lng').value)});
 return {...base,incluyeVivienda:withHouse,areaCasa:withHouse?Number($('#areaCasa').value||0):0,materialCasa:$('#materialCasa').value,anioConstruccion:Number($('#anioConstruccion').value||0),estadoCasa:$('#estadoCasa').value,tipoFundacion:'sin_fundacion',anioRemodelacion:Number($('#anioRemodelacion').value||0),remodelacionIntegral:Number($('#anioRemodelacion').value||0)>0,dormitorios:Number($('#dormitorios').value||0),banos:Number($('#banos').value||0),pisos:Number($('#pisos').value||1),obrasAdicionales:obras,caracteristicaDiferenciadora:$('#caracteristicaDiferenciadora').value};
}
function nearestCityFor(x){try{const city=catalog?.getCityForCommune?.(x.comuna,x.region)||null;return city?{name:city.name,category:city.category||'',weight:Number(city.weight||1)}:null}catch{return null}}
function validate(x){if(!x.region)return 'Selecciona una región.';if(!x.comuna)return 'Selecciona una comuna.';if(!x.area)return 'Ingresa la superficie del terreno.';if(!Number.isFinite(x.distanceKm)||x.distanceKm<0)return 'Ingresa una distancia válida a la ciudad principal.';if(x.incluyeVivienda&&!x.areaCasa)return 'Si incluye vivienda, indica sus m² construidos.';return ''}
function calculate(ev){
 ev?.preventDefault();const x=inputs();const error=validate(x);if(error){$('#status').textContent=error;$('#result').hidden=true;return}
 x.nearestCity=nearestCityFor(x);let res=x.incluyeVivienda?window.TPLHouseEngine?.calculate(x):window.TPLLandEngine?.calculate(x);
 if(!res||res.error){$('#status').textContent=res?.error||'No fue posible calcular. Revisa los datos.';$('#result').hidden=true;return}
 lastResult=res;lastInput=x;$('#status').textContent=mode==='precisa'?'Tasación precisa calculada con los antecedentes disponibles.':'Tasación rápida calculada. Puedes pasar a Precisa para enriquecer el análisis.';$('#result').hidden=false;
 $('#ideal').textContent=money(res.ideal);$('#quick').textContent=money(res.quick);$('#patient').textContent=money(res.patient);
 const b=res.desglose||{valorTerreno:res.ideal};const labels={valorTerreno:'Terreno',valorCasa:'Vivienda',valorFundacion:'Fundación',sumaObrasAdicionales:'Obras adicionales','bonificaciónDiferenciadora':'Característica diferenciadora'};
 $('#breakdown').innerHTML=Object.entries(labels).filter(([k])=>Number(b[k])).map(([k,l])=>`<div class="breakdown-row"><span>${l}</span><strong>${money(b[k])}</strong></div>`).join('')||`<div class="breakdown-row"><span>Terreno</span><strong>${money(res.ideal)}</strong></div>`;
 const mr=res.marketReference||res.landResult?.marketReference||null,box=$('#marketReference');if(mr){box.hidden=false;box.innerHTML=`<small>Referencia comunal disponible</small><strong>${money(mr.medianM2)}/m²</strong><span>Rango central ${money(mr.p25M2)}–${money(mr.p75M2)}/m² · confianza ${String(mr.confidence||'referencial').replace('-',' ')}</span>`}else box.hidden=true;
 const q=new URLSearchParams({region:x.region,comuna:x.comuna,superficie:x.area,tasacion:String(Math.round(res.ideal)),tipo:x.incluyeVivienda?'casa':'parcela'});$('#publishLink').href=`index.html?${q.toString()}`;
}
function row(label,value){if(value===undefined||value===null||String(value).trim()==='')return '';return `<tr><td>${label}</td><td>${value}</td></tr>`}
function haversine(a,b){const R=6371,r=v=>v*Math.PI/180,dlat=r(b.lat-a.lat),dlng=r(b.lng-a.lng),h=Math.sin(dlat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dlng/2)**2;return R*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
async function nearbyHTML(x){if(!Number.isFinite(x.lat)||!Number.isFinite(x.lng)||!x.lat||!x.lng)return '<p class="muted">Agrega coordenadas en Tasación precisa para calcular servicios cercanos.</p>';const q=`[out:json][timeout:15];(nwr(around:20000,${x.lat},${x.lng})["amenity"~"hospital|clinic|doctors|police|school|fuel|pharmacy|marketplace"];nwr(around:20000,${x.lat},${x.lng})["shop"~"supermarket|convenience"];);out center tags;`;try{const r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:'data='+encodeURIComponent(q)});if(!r.ok)throw 0;const j=await r.json(),els=(j.elements||[]).map(e=>{const lat=Number(e.lat??e.center?.lat),lng=Number(e.lon??e.center?.lon);return {...e,d:Number.isFinite(lat)&&Number.isFinite(lng)?haversine({lat:x.lat,lng:x.lng},{lat,lng}):Infinity}}).filter(e=>Number.isFinite(e.d));const cats=[['Salud',t=>/hospital|clinic|doctors/.test(t.amenity||'')],['Carabineros / policía',t=>(t.amenity||'')==='police'],['Supermercado / comercio',t=>/supermarket|convenience/.test(t.shop||'')||(t.amenity||'')==='marketplace'],['Educación',t=>(t.amenity||'')==='school'],['Servicentro',t=>(t.amenity||'')==='fuel'],['Farmacia',t=>(t.amenity||'')==='pharmacy']];const out=cats.map(([l,test])=>{const f=els.filter(e=>test(e.tags||{})).sort((a,b)=>a.d-b.d)[0];return f?`<div class="near-item"><strong>${l}</strong><span>${f.tags?.name||l} · ${f.d.toFixed(1).replace('.',',')} km aprox.</span></div>`:''}).filter(Boolean).join('');return out?`<div class="near-grid">${out}</div>`:'<p class="muted">No se encontraron suficientes servicios cercanos.</p>'}catch{return '<p class="muted">No fue posible consultar cercanías en este momento.</p>'}}
async function openPremium(){if(!lastResult||!lastInput)return;const x=lastInput,r=lastResult,mr=r.marketReference||r.landResult?.marketReference||null,c=$('#premiumContent');c.innerHTML='<p>Preparando informe…</p>';$('#premiumDialog').showModal();const nearby=await nearbyHTML(x);c.innerHTML=`<section><h2>${x.incluyeVivienda?'Propiedad rural con vivienda':'Parcela / campo'} en ${x.comuna}</h2><p class="muted">Informe construido con los antecedentes ingresados en modo ${x.mode==='precisa'?'preciso':'rápido'}.</p></section><section class="premium-value"><small>Valor recomendado TPL</small><strong>${money(r.ideal)}</strong><span>Venta rápida ${money(r.quick)} · Venta paciente ${money(r.patient)}</span></section>${mr?`<section><h3>Referencia comunal</h3><p>Mediana observada: <strong>${money(mr.medianM2)}/m²</strong>. Rango central: ${money(mr.p25M2)}–${money(mr.p75M2)}/m². Confianza ${String(mr.confidence||'referencial').replace('-',' ')}.</p></section>`:''}<section><h3>Antecedentes</h3><table>${row('Región',x.region)}${row('Comuna',x.comuna)}${row('Superficie',`${x.area.toLocaleString('es-CL')} m²`)}${row('Distancia a ciudad',`${x.distanceKm} km`)}${row('Rol',x.rol)}${row('Electricidad',x.electricity)}${row('Agua',x.water)}${row('Topografía',x.topography)}${x.mode==='precisa'?row('Acceso',x.access)+row('Suelo',x.soil)+row('Exposición solar',x.exposure)+row('Vista',x.view)+row('Vegetación',x.vegetation)+row('Cierre',x.fencing)+row('Acceso controlado',x.gate)+row('Condominio',x.condominium)+row('Distancia a ruta',`${x.routeDistanceKm||0} km`):''}${x.incluyeVivienda?row('Casa',`${x.areaCasa} m²`)+row('Material',x.materialCasa)+row('Dormitorios',x.dormitorios)+row('Baños',x.banos)+row('Estado',x.estadoCasa):''}</table></section><section><h3>Cercanías y conectividad</h3>${nearby}</section><section><h3>Observación TPL</h3><p class="muted">La precisión mejora cuando se entregan ubicación exacta y antecedentes completos. Los campos sin una regla económica aprobada no modifican arbitrariamente el valor: quedan registrados para análisis, comparables e Informe Premium.</p></section>`}
function useLocation(){if(!navigator.geolocation){alert('Tu navegador no permite geolocalización.');return}const b=$('#useMyLocation');b.disabled=true;b.textContent='Obteniendo ubicación…';navigator.geolocation.getCurrentPosition(p=>{$('#lat').value=p.coords.latitude.toFixed(6);$('#lng').value=p.coords.longitude.toFixed(6);b.disabled=false;b.textContent='Ubicación cargada'},()=>{b.disabled=false;b.textContent='Usar mi ubicación actual';alert('No pudimos obtener tu ubicación.')},{enableHighAccuracy:true,timeout:10000})}
document.addEventListener('DOMContentLoaded',async()=>{buildWorks();await fillRegions();document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));setMode('rapida');$('#incluyeVivienda').addEventListener('change',e=>$('#houseFields').hidden=!e.target.checked);$('#tasadorForm').addEventListener('submit',calculate);$('#useMyLocation').onclick=useLocation;$('#premiumReportBtn').onclick=openPremium;$('#closePremium').onclick=()=>$('#premiumDialog').close()});
