(()=>{
  'use strict';
  const $=id=>document.getElementById(id);
  const params=new URLSearchParams(location.search);
  const format=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(n)||0);
  const number=v=>Number(String(v??'').replace(/[^0-9.-]/g,''))||0;
  const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const lexicalParcels=(()=>{try{return typeof parcelas!=='undefined'&&Array.isArray(parcelas)?parcelas:[]}catch{return[]}})();
  const parcels=Array.isArray(window.parcelas)?window.parcelas:(lexicalParcels.length?lexicalParcels:(Array.isArray(window.parcelasPortal)?window.parcelasPortal:[]));
  const houses=Array.isArray(window.casas)?window.casas:[];
  const parcelId=params.get('parcela')||params.get('parcelaId')||localStorage.getItem('selectedParcelaId');
  const houseId=params.get('casa')||params.get('casaId');
  const budget=number(params.get('presupuesto'));
  let selectedParcelData=null;try{selectedParcelData=JSON.parse(localStorage.getItem('selectedParcelaData')||'null')}catch{}
  const parcel=parcels.find(p=>String(p.id)===String(parcelId))||(selectedParcelData&&String(selectedParcelData.id)===String(parcelId)?selectedParcelData:null)||{};
  const parcelFound=Boolean(parcel&&parcel.id);
  const state={housing:params.get('tipo')||'',house:null,m2:72,rooms:3,material:null};
  const materials=[
    {id:'madera-economica',name:'Madera económica',priceM2:350000,desc:'Construcción cálida y de rápida ejecución. Extras e instalaciones se revisan por separado.',included:['Radier base']},
    {id:'metalcon-estandar',name:'Metalcon estándar',priceM2:420000,desc:'Estructura liviana, aislación eficiente y mantención moderada.',included:['Radier base','Instalación eléctrica','Instalación sanitaria']},
    {id:'premium',name:'Premium',priceM2:550000,desc:'Mejores terminaciones, instalaciones y equipamiento principal incluidos.',included:['Radier base','Instalación eléctrica','Instalación sanitaria','Artefactos de cocina y baño']},
    {id:'cemento-solido',name:'Cemento sólido',priceM2:720000,desc:'Mayor durabilidad y sensación de construcción definitiva.',included:['Radier base','Instalación eléctrica','Instalación sanitaria','Artefactos de cocina y baño']}
  ];
  function parcelPrice(){return number(parcel.precio||parcel.valor||parcel.price)}
  function parcelSize(){return number(parcel.tamano||parcel.superficie||parcel.m2)}
  function housePrice(){if(state.housing==='prefabricada')return number(state.house?.valorCasa||state.house?.precio||state.house?.valor);if(state.housing==='diseno-propio'&&state.material)return state.m2*state.material.priceM2;return 0}
  function total(){return parcelPrice()+housePrice()}
  function imagePath(path){if(!path)return './assets/logo-tu-parcela-lista.png';if(/^https?:|^data:|^blob:/.test(path))return path;return `./${String(path).replace(/^\.\//,'')}`}
  function parcelVirtues(){const out=[];const text=normalize([parcel.descripcion,parcel.detalle].join(' '));if(parcel.agua||text.includes('agua'))out.push('Agua informada');if(parcel.luz||parcel.electricidad||text.includes('electric'))out.push('Electricidad');if(parcel.rol||text.includes('rol propio'))out.push('Rol informado');if(parcel.naturaleza||/bosque|nativ|rio|lago|vista/.test(text))out.push('Entorno natural');if(parcel.facilidad||parcel.facilidad_pago)out.push('Facilidad de pago');return out.slice(0,5)}
  function renderParcel(){const imgs=(Array.isArray(parcel.imagenes)?parcel.imagenes:[parcel.imagen]).filter(Boolean);$('parcel-image').src=imagePath(imgs[0]);$('parcel-name').textContent=parcel.nombre||'Parcela seleccionada';$('parcel-meta').textContent=`${parcel.comuna||'Comuna por confirmar'} · ${parcelSize()?parcelSize().toLocaleString('es-CL')+' m²':'Superficie por confirmar'} · ${parcel.precio||format(parcelPrice())}`;$('parcel-virtues').innerHTML=parcelVirtues().map(v=>`<span>${v}</span>`).join('')||'<span>Proyecto en evaluación TPL</span>'}
  function houseClass(h){const m=number(h.metros||h.mt2||h.superficie);return m<60?'small':m<110?'medium':'large'}
  function houseRooms(h){return number(h.habitaciones||h.dormitorios)||1}
  function renderPrefab(){const room=$('prefab-rooms').value,size=$('prefab-size').value;let list=houses.filter(h=>(room==='all'||(room==='4'?houseRooms(h)>=4:houseRooms(h)===number(room)))&&(size==='all'||houseClass(h)===size));if(budget){const available=Math.max(0,budget-parcelPrice());list=list.sort((a,b)=>Math.abs(number(a.valorCasa)-available)-Math.abs(number(b.valorCasa)-available))}else list=list.sort((a,b)=>number(a.valorCasa)-number(b.valorCasa));$('prefab-grid').innerHTML=list.map(h=>`<button type="button" class="prefab-card ${state.house?.id===h.id?'active':''}" data-house="${h.id}"><img loading="lazy" decoding="async" src="${imagePath(h.foto||(h.imagenes||[])[0])}" alt="${h.nombre||'Casa prefabricada'}"><span class="body"><strong>${h.nombre||'Casa prefabricada'}</strong><small>${h.empresa?`${h.empresa} · `:''}${number(h.metros)} m² · ${houseRooms(h)} dormitorio(s) · ${h.tiempo||'Plazo por confirmar'}</small><span class="price">${format(h.valorCasa)}</span><small>Valor base. Instalación sujeta a modelo y ubicación.</small></span></button>`).join('')||'<p>No encontramos modelos para este filtro.</p>';document.querySelectorAll('[data-house]').forEach(btn=>btn.onclick=()=>{state.house=houses.find(h=>String(h.id)===btn.dataset.house);state.m2=number(state.house?.metros);state.rooms=houseRooms(state.house);renderPrefab();updateSummary()})}
  function renderMaterials(){$('material-grid').innerHTML=materials.map(m=>`<button type="button" class="material-card ${state.material?.id===m.id?'active':''}" data-material="${m.id}"><strong>${m.name}</strong><small>${m.desc}</small><span class="price">${format(m.priceM2)} / m²</span><small>Incluye: ${m.included.join(', ')}</small></button>`).join('');document.querySelectorAll('[data-material]').forEach(btn=>btn.onclick=()=>{state.material=materials.find(m=>m.id===btn.dataset.material);renderMaterials();updateSummary()})}
  function advisorText(){if(!state.housing)return'Elige casa prefabricada o diseño propio para continuar.';if(state.housing==='prefabricada'&&!state.house)return'Te mostraremos primero los modelos más cercanos a tu presupuesto disponible.';if(state.housing==='diseno-propio'&&!state.material)return'Elige superficie y material para calcular el valor estimado.';if(!budget)return'Ya tienes un subtotal base de parcela + vivienda. Los costos de instalación y terreno se confirman en la siguiente etapa.';const diff=budget-total();if(diff>=3000000)return`Tu proyecto se mantiene dentro del presupuesto y deja aproximadamente ${format(diff)} para terreno, permisos o extras.`;if(diff>=0)return`Tu proyecto está muy cerca del presupuesto máximo. Aún queda un margen aproximado de ${format(diff)}.`;return`Esta alternativa supera tu presupuesto en aproximadamente ${format(Math.abs(diff))}. Puedes ajustar metros cuadrados, material o modelo.`}
  function updateSummary(){$('sum-parcel').textContent=format(parcelPrice());$('sum-house').textContent=housePrice()?format(housePrice()):'Por definir';$('sum-size').textContent=state.housing==='prefabricada'&&state.house?`${state.m2} m² · ${state.rooms} dormitorio(s)`:state.housing==='diseno-propio'?`${state.m2} m² · ${state.rooms} dormitorio(s)`:'—';$('sum-total').textContent=format(total());$('summary-advice').textContent=advisorText();if(budget){$('budget-box').hidden=false;$('sum-budget').textContent=format(budget);const d=budget-total();$('budget-difference').textContent=d>=0?`Disponible estimado: ${format(d)}`:`Supera el presupuesto por ${format(Math.abs(d))}`}}
  function setHousing(type){state.housing=type;document.querySelectorAll('[data-housing]').forEach(b=>b.classList.toggle('active',b.dataset.housing===type));$('prefab-panel').hidden=type!=='prefabricada';$('custom-panel').hidden=type!=='diseno-propio';if(type==='prefabricada')renderPrefab();if(type==='diseno-propio')renderMaterials();updateSummary();setTimeout(()=>$(type==='prefabricada'?'prefab-panel':'custom-panel').scrollIntoView({behavior:'smooth',block:'start'}),50)}
  function projectPayload(){return{id:`tpl-${Date.now()}`,createdAt:new Date().toISOString(),parcelId:parcel.id,parcelName:parcel.nombre,parcelCommune:parcel.comuna,parcelPrice:parcelPrice(),parcelSize:parcelSize(),parcelData:parcel,housing:state.housing,houseId:state.house?.id||null,houseName:state.house?.nombre||null,houseData:state.house||null,m2:state.m2,rooms:state.rooms,material:state.material?.name||null,materialData:state.material||null,housePrice:housePrice(),total:total(),budget,client:{name:$('client-name').value.trim(),phone:$('client-phone').value.trim(),email:$('client-email').value.trim(),commune:$('client-commune').value.trim()},source:{origin:params.get('origen'),priority:params.get('prioridad'),distance:params.get('distancia'),from:'cotizador'}}}
  function validateClient(){if(!parcelFound){$('save-status').textContent='No pudimos recuperar la parcela seleccionada. Vuelve a la ficha y elige vivienda nuevamente.';return false}if(!state.housing||(state.housing==='prefabricada'&&!state.house)||(state.housing==='diseno-propio'&&!state.material)){$('save-status').textContent='Completa primero la vivienda para crear tu proyecto.';return false}if(!$('client-name').value.trim()||!$('client-phone').value.trim()){ $('save-status').textContent='Ingresa tu nombre y WhatsApp para continuar.';return false}if(!$('client-consent').checked){$('save-status').textContent='Debes autorizar el contacto para guardar o solicitar acciones.';return false}return true}
  function saveProject(){if(!validateClient())return null;const p=projectPayload();const list=JSON.parse(localStorage.getItem('tpl_v2_projects')||'[]');list.unshift(p);localStorage.setItem('tpl_v2_projects',JSON.stringify(list.slice(0,20)));localStorage.setItem('tpl_v2_current_project',JSON.stringify(p));$('save-status').textContent='Proyecto preparado. Continuarás con un resumen claro de costos y próximos pasos.';return p}
  function whatsappText(p){return `Mi proyecto TPL\n\nParcela: ${p.parcelName||'Por definir'}\nComuna: ${p.parcelCommune||'Por confirmar'}\nValor parcela: ${format(p.parcelPrice)}\nVivienda: ${p.housing==='prefabricada'?(p.houseName||'Casa prefabricada'):`Diseño propio · ${p.m2} m² · ${p.material||'Material por definir'}`}\nDormitorios: ${p.rooms}\nValor vivienda: ${format(p.housePrice)}\nSubtotal base parcela + vivienda: ${format(p.total)}${p.budget?`\nPresupuesto: ${format(p.budget)}`:''}\n\nEnlace: ${location.href}`}
  function sendWhatsApp(){const p=saveProject();if(!p)return;let digits=p.client.phone.replace(/\D/g,'');if(digits.startsWith('9')&&digits.length===9)digits='56'+digits;window.open(`https://wa.me/${digits}?text=${encodeURIComponent(whatsappText(p))}`,'_blank','noopener')}
  function request(kind,extra={}){const p=saveProject();if(!p)return;const req={kind,status:'pendiente',createdAt:new Date().toISOString(),project:p,...extra};const list=JSON.parse(localStorage.getItem('tpl_v2_requests')||'[]');list.unshift(req);localStorage.setItem('tpl_v2_requests',JSON.stringify(list.slice(0,30)));$('save-status').textContent=kind==='asesoria'?'Solicitud de asesoría guardada.':'Solicitud guardada. Un asesor deberá confirmar el siguiente paso.'}
  document.querySelectorAll('[data-housing]').forEach(b=>b.onclick=()=>setHousing(b.dataset.housing));
  document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-size]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.m2=number(b.dataset.size);$('custom-m2').value=state.m2;updateSummary()});
  $('custom-m2').oninput=e=>{state.m2=Math.max(18,number(e.target.value));updateSummary()};$('custom-rooms').oninput=e=>{state.rooms=Math.max(1,number(e.target.value));updateSummary()};$('prefab-rooms').onchange=renderPrefab;$('prefab-size').onchange=renderPrefab;
  $('send-whatsapp').onclick=sendWhatsApp;
  $('open-project').onclick=()=>{const p=saveProject();if(!p)return;location.href=`./proyecto.html?id=${encodeURIComponent(p.id)}`};
  renderParcel();renderMaterials();updateSummary();if(!parcelFound){$('parcel-name').textContent='Parcela no recuperada';$('parcel-meta').textContent='Vuelve a parcela.html y selecciona nuevamente la vivienda.';$('save-status').textContent='No se encontró la parcela indicada. No continuaremos con un valor $0 ni con otra parcela por defecto.';}if(houseId){state.house=houses.find(h=>String(h.id)===String(houseId))||null;if(state.house){state.m2=number(state.house.metros);state.rooms=houseRooms(state.house);setHousing('prefabricada')}}else if(state.housing)setHousing(state.housing);
})();
