import type {
  HouseModel,
  ConstructionSystemRate,
  FoundationOption,
  AdditionalWorkItem,
} from "./types";

/**
 * Catálogo canónico de modelos de casas prefabricadas y diseños de referencia.
 * Portado directamente desde `frontend-v2/casas.js` (ADN original TPL).
 */
export const HOUSE_MODELS: HouseModel[] = [
  {
    id: "aura18",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 18m²",
    metros: 18,
    habitaciones: 1,
    banos: 1,
    valorCasa: 2490000,
    foto: "image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_foto_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_foto.webp",
      "image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "20 días",
  },
  {
    id: "aura24",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 24m²",
    metros: 24,
    habitaciones: 2,
    banos: 1,
    valorCasa: 3350000,
    foto: "image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_foto_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_foto.webp",
      "image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "20 días",
  },
  {
    id: "aura36",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 36m²",
    metros: 36,
    habitaciones: 2,
    banos: 1,
    valorCasa: 4840000,
    foto: "image/casas/pre_fabricadas/36mts2/pequenas/36_caida_agua_foto_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/pequenas/36_caida_agua_foto.webp",
      "image/casas/pre_fabricadas/36mts2/pequenas/36_caida_agua_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "20 días",
  },
  {
    id: "aura42",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 42m²",
    metros: 42,
    habitaciones: 3,
    banos: 1,
    valorCasa: 5600000,
    foto: "image/casas/pre_fabricadas/36mts2/medianas/42_caida_agua_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/medianas/42_caida_agua_foto.webp",
      "image/casas/pre_fabricadas/36mts2/medianas/42_caida_agua_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "25 días",
  },
  {
    id: "aura48",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 48m²",
    metros: 48,
    habitaciones: 3,
    banos: 1,
    valorCasa: 5950000,
    foto: "image/casas/pre_fabricadas/36mts2/medianas/48_caida_agua_render.webp",
    imagenes: ["image/casas/pre_fabricadas/36mts2/medianas/48_caida_agua_plano.webp"],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "25 días",
  },
  {
    id: "aura54",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 54m²",
    metros: 54,
    habitaciones: 3,
    banos: 1,
    valorCasa: 6750000,
    foto: "image/casas/pre_fabricadas/36mts2/medianas/54_6caida_agua_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/medianas/54_6caida_agua_render.webp",
      "image/casas/pre_fabricadas/36mts2/medianas/54_6caida_agua_foto.webp",
      "image/casas/pre_fabricadas/36mts2/medianas/54_6caida_agua_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "25 días",
  },
  {
    id: "aura72",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 72m²",
    metros: 72,
    habitaciones: 3,
    banos: 2,
    valorCasa: 8750000,
    foto: "image/casas/pre_fabricadas/36mts2/medianas/72_2a_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/medianas/72_2a_render.webp",
      "image/casas/pre_fabricadas/36mts2/medianas/72_2a_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "35 días",
  },
  {
    id: "aura84_1",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 82m²",
    metros: 84,
    habitaciones: 4,
    banos: 2,
    valorCasa: 9200000,
    foto: "image/casas/pre_fabricadas/36mts2/grandes/82_caida_agua_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/grandes/82_caida_agua_foto.webp",
      "image/casas/pre_fabricadas/36mts2/grandes/82_caida_agua_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "25 días",
  },
  {
    id: "aura84_2",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 84m² de 6 aguas",
    metros: 84,
    habitaciones: 4,
    banos: 2,
    valorCasa: 9900000,
    foto: "image/casas/pre_fabricadas/36mts2/grandes/84_6caida_agua_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/grandes/84_6caida_agua_foto.webp",
      "image/casas/pre_fabricadas/36mts2/grandes/84_6caida_agua_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "25 días",
  },
  {
    id: "aura108",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 108m² de 6 aguas",
    metros: 108,
    habitaciones: 6,
    banos: 2,
    valorCasa: 13500000,
    foto: "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_foto.webp",
      "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_render.webp",
    ],
    plano: "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_plano.webp",
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "25 días",
  },
  {
    id: "aura120",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 120m² de 6 aguas",
    metros: 120,
    habitaciones: 6,
    banos: 2,
    valorCasa: 14700000,
    foto: "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_foto.webp",
      "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_plano.webp",
    ],
    plano: "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_plano.webp",
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "25 días",
  },
  {
    id: "Innova18",
    tipo: "prefabricada",
    empresa: "Innova",
    nombre: "Casa Moderna madera full 18m²",
    metros: 18,
    habitaciones: 1,
    banos: 1,
    valorCasa: 6300000,
    foto: "image/casas/pro/innova/innova_1_habitacion_foto.webp",
    imagenes: [
      "image/casas/pro/innova/innova_1_habitacion_foto.webp",
      "image/casas/pro/innova/innova_1_habitacion_plano.webp",
    ],
    plano: "image/casas/pro/innova/innova_1_habitacion_plano.webp",
    descripcionBreve: "Valor incluye todo hasta piso cerámico o piso flotante, llegar y habitar.",
    tiempoEstimado: "25 días",
  },
  {
    id: "Innova54",
    tipo: "prefabricada",
    empresa: "Innova",
    nombre: "Casa Moderna completa full 54m²",
    metros: 54,
    habitaciones: 3,
    banos: 1,
    valorCasa: 12600000,
    foto: "image/casas/pro/innova/innova_3_habitaciones_foto_1.webp",
    imagenes: [
      "image/casas/pro/innova/innova_3_habitaciones_foto_1.webp",
      "image/casas/pro/innova/innova_3_habitaciones_foto_2.webp",
    ],
    descripcionBreve: "Valor incluye todo hasta piso cerámico o piso flotante, llegar y habitar.",
    tiempoEstimado: "25 días",
  },
  {
    id: "Nogal72",
    tipo: "prefabricada",
    empresa: "Los Nogales",
    nombre: "Casa Moderna completa full 72m²",
    metros: 72,
    habitaciones: 3,
    banos: 2,
    valorCasa: 28000000,
    foto: "image/casas/pro/nogales/Alfa_72_mt2_.webp",
    imagenes: [
      "image/casas/pro/nogales/Alfa_72_mt2_.webp",
      "image/casas/pro/nogales/Alfa_72_mt2_plano.webp",
    ],
    descripcionBreve: "Valor incluye todo hasta piso cerámico o flotante con llaves en mano.",
    tiempoEstimado: "25 días",
  },
];

/**
 * Tarifas oficiales de sistemas constructivos a medida ($ / m²).
 */
export const CONSTRUCTION_SYSTEM_RATES: Record<string, ConstructionSystemRate> = {
  madera: {
    id: "madera",
    nombre: "Madera impregnada",
    descripcion: "Construcción rápida, excelente calidez térmica y costo eficiente.",
    valorM2: 270000,
  },
  metalcon: {
    id: "metalcon",
    nombre: "Metalcon / Paneles SIP",
    descripcion: "Estructura metálica liviana de alta precisión y máxima aislación energética.",
    valorM2: 370000,
  },
  premium: {
    id: "premium",
    nombre: "Diseño Premium Llave en Mano",
    descripcion: "Vivienda contemporánea con terminaciones superiores y arquitectura de autor.",
    valorM2: 420000,
  },
  hormigon: {
    id: "hormigon",
    nombre: "Hormigón / Sólido",
    descripcion: "Construcción tradicional de máxima robustez, durabilidad y aislación acústica.",
    valorM2: 720000,
  },
};

/**
 * Catálogo de fundaciones (base estructural según tipo de suelo).
 */
export const FOUNDATION_OPTIONS: FoundationOption[] = [
  {
    id: "pilotes_madera",
    nombre: "Instalación en pilotes de madera impregnada",
    tipoCalculo: "mt2",
    valorPorM2: 60000,
    empresa: "Nogales Constructora",
  },
  {
    id: "radier_hormigon",
    nombre: "Radier de hormigón armado estándar",
    tipoCalculo: "mt2",
    valorPorM2: 95000,
    empresa: "Nogales Constructora",
  },
  {
    id: "radier_full_terminado",
    nombre: "Radier completo con piso cerámico llave en mano",
    tipoCalculo: "mt2",
    valorPorM2: 140000,
    empresa: "Nogales Constructora",
  },
];

/**
 * Catálogo de obras complementarias rurales portadas de `extras.js`.
 */
export const ADDITIONAL_WORKS: AdditionalWorkItem[] = [
  {
    id: "pozo_profundo",
    nombre: "Pozo profundo de agua potable (según metros)",
    tipoCalculo: "metro",
    valorUnitario: 50000,
    defaultQty: 30,
    minQty: 10,
    maxQty: 80,
    descripcion: "Excavación e entubado de pozo profundo (estimado base 30 metros).",
  },
  {
    id: "fosa_septica",
    nombre: "Fosa séptica con kit de drenaje e instalación",
    tipoCalculo: "unidad",
    valorUnitario: 1500000,
    defaultQty: 1,
    minQty: 1,
    maxQty: 3,
    descripcion: "Sistema de tratamiento biológico para aguas servidas con cámara desgrasadora.",
  },
  {
    id: "empalme_electrico",
    nombre: "Empalme eléctrico / acometida a red",
    tipoCalculo: "unidad",
    valorUnitario: 1500000,
    defaultQty: 1,
    minQty: 1,
    maxQty: 2,
    descripcion: "Poste de acometida, caja de medidor y tramitación técnica ante distribuidora.",
  },
  {
    id: "cierre_perimetral",
    nombre: "Cierre perimetral con polines y alambre de púas",
    tipoCalculo: "metro",
    valorUnitario: 2000,
    defaultQty: 200,
    minQty: 50,
    maxQty: 600,
    descripcion: "Cerco tradicional de campo con polines de pino impregnado y 4 hebras.",
  },
  {
    id: "porton_acceso",
    nombre: "Portón de acceso vehicular rústico",
    tipoCalculo: "unidad",
    valorUnitario: 1200000,
    defaultQty: 1,
    minQty: 1,
    maxQty: 2,
    descripcion: "Portón de doble hoja en madera y fierro para entrada principal.",
  },
];
