import type {
  HouseModel,
  ConstructionSystemRate,
  FoundationOption,
  AdditionalWorkItem,
} from "./types";

/**
 * Catálogo canónico de modelos de casas prefabricadas y diseños de referencia.
 * Portado directamente desde `frontend-v2/casas.js` (ADN original TPL).
 */
export const HOUSE_MODELS: HouseModel[] = [
  {
    id: "aura18",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 18m²",
    metros: 18,
    habitaciones: 1,
    banos: 1,
    valorCasa: 2490000,
    foto: "image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_foto_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_foto.webp",
      "image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "20 días",
  },
  {
    id: "aura24",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 24m²",
    metros: 24,
    habitaciones: 2,
    banos: 1,
    valorCasa: 3350000,
    foto: "image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_foto_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_foto.webp",
      "image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "20 días",
  },
  {
    id: "aura36",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 36m²",
    metros: 36,
    habitaciones: 2,
    banos: 1,
    valorCasa: 4840000,
    foto: "image/casas/pre_fabricadas/36mts2/pequenas/36_caida_agua_foto_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/pequenas/36_caida_agua_foto.webp",
      "image/casas/pre_fabricadas/36mts2/pequenas/36_caida_agua_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "20 días",
  },
  {
    id: "aura42",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 42m²",
    metros: 42,
    habitaciones: 3,
    banos: 1,
    valorCasa: 5600000,
    foto: "image/casas/pre_fabricadas/36mts2/medianas/42_caida_agua_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/medianas/42_caida_agua_foto.webp",
      "image/casas/pre_fabricadas/36mts2/medianas/42_caida_agua_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "25 días",
  },
  {
    id: "aura48",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 48m²",
    metros: 48,
    habitaciones: 3,
    banos: 1,
    valorCasa: 5950000,
    foto: "image/casas/pre_fabricadas/36mts2/medianas/48_caida_agua_render.webp",
    imagenes: ["image/casas/pre_fabricadas/36mts2/medianas/48_caida_agua_plano.webp"],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "25 días",
  },
  {
    id: "aura54",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 54m²",
    metros: 54,
    habitaciones: 3,
    banos: 1,
    valorCasa: 6750000,
    foto: "image/casas/pre_fabricadas/36mts2/medianas/54_6caida_agua_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/medianas/54_6caida_agua_render.webp",
      "image/casas/pre_fabricadas/36mts2/medianas/54_6caida_agua_foto.webp",
      "image/casas/pre_fabricadas/36mts2/medianas/54_6caida_agua_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "25 días",
  },
  {
    id: "aura72",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 72m²",
    metros: 72,
    habitaciones: 3,
    banos: 2,
    valorCasa: 8750000,
    foto: "image/casas/pre_fabricadas/36mts2/medianas/72_2a_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/medianas/72_2a_render.webp",
      "image/casas/pre_fabricadas/36mts2/medianas/72_2a_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "35 días",
  },
  {
    id: "aura84_1",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 82m²",
    metros: 84,
    habitaciones: 4,
    banos: 2,
    valorCasa: 9200000,
    foto: "image/casas/pre_fabricadas/36mts2/grandes/82_caida_agua_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/grandes/82_caida_agua_foto.webp",
      "image/casas/pre_fabricadas/36mts2/grandes/82_caida_agua_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "25 días",
  },
  {
    id: "aura84_2",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 84m² de 6 aguas",
    metros: 84,
    habitaciones: 4,
    banos: 2,
    valorCasa: 9900000,
    foto: "image/casas/pre_fabricadas/36mts2/grandes/84_6caida_agua_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/grandes/84_6caida_agua_foto.webp",
      "image/casas/pre_fabricadas/36mts2/grandes/84_6caida_agua_plano.webp",
    ],
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "25 días",
  },
  {
    id: "aura108",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 108m² de 6 aguas",
    metros: 108,
    habitaciones: 6,
    banos: 2,
    valorCasa: 13500000,
    foto: "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_foto.webp",
      "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_render.webp",
    ],
    plano: "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_plano.webp",
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "25 días",
  },
  {
    id: "aura120",
    tipo: "prefabricada",
    empresa: "ChileHome",
    nombre: "Casa prefabricada 120m² de 6 aguas",
    metros: 120,
    habitaciones: 6,
    banos: 2,
    valorCasa: 14700000,
    foto: "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_render.webp",
    imagenes: [
      "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_foto.webp",
      "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_plano.webp",
    ],
    plano: "image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_plano.webp",
    descripcionBreve: "Modelo full viene con estructura madera, techumbre, piso, forros int y ext, puertas y ventanas.",
    tiempoEstimado: "25 días",
  },
  {
    id: "Innova18",
    tipo: "prefabricada",
    empresa: "Innova",
    nombre: "Casa Moderna madera full 18m²",
    metros: 18,
    habitaciones: 1,
    banos: 1,
    valorCasa: 6300000,
    foto: "image/casas/pro/innova/innova_1_habitacion_foto.webp",
    imagenes: [
      "image/casas/pro/innova/innova_1_habitacion_foto.webp",
      "image/casas/pro/innova/innova_1_habitacion_plano.webp",
    ],
    plano: "image/casas/pro/innova/innova_1_habitacion_plano.webp",
    descripcionBreve: "Valor incluye todo hasta piso cerámico o piso flotante, llegar y habitar.",
    tiempoEstimado: "25 días",
  },
  {
    id: "Innova54",
    tipo: "prefabricada",
    empresa: "Innova",
    nombre: "Casa Moderna completa full 54m²",
    metros: 54,
    habitaciones: 3,
    banos: 1,
    valorCasa: 12600000,
    foto: "image/casas/pro/innova/innova_3_habitaciones_foto_1.webp",
    imagenes: [
      "image/casas/pro/innova/innova_3_habitaciones_foto_1.webp",
      "image/casas/pro/innova/innova_3_habitaciones_foto_2.webp",
    ],
    descripcionBreve: "Valor incluye todo hasta piso cerámico o piso flotante, llegar y habitar.",
    tiempoEstimado: "25 días",
  },
  {
    id: "Nogal72",
    tipo: "prefabricada",
    empresa: "Los Nogales",
    nombre: "Casa Moderna completa full 72m²",
    metros: 72,
    habitaciones: 3,
    banos: 2,
    valorCasa: 28000000,
    foto: "image/casas/pro/nogales/Alfa_72_mt2_.webp",
    imagenes: [
      "image/casas/pro/nogales/Alfa_72_mt2_.webp",
      "image/casas/pro/nogales/Alfa_72_mt2_plano.webp",
    ],
    descripcionBreve: "Valor incluye todo hasta piso cerámico o flotante con llaves en mano.",
    tiempoEstimado: "25 días",
  },
];

/**
 * Tarifas oficiales de sistemas constructivos a medida ($ / m²).
 */
export const CONSTRUCTION_SYSTEM_RATES: Record<string, ConstructionSystemRate> = {
  madera: {
    id: "madera",
    nombre: "Madera impregnada",
    descripcion: "Construcción rápida, excelente calidez térmica y costo eficiente.",
    valorM2: 270000,
  },
  metalcon: {
    id: "metalcon",
    nombre: "Metalcon / Paneles SIP",
    descripcion: "Estructura metálica liviana de alta precisión y máxima aislación energética.",
    valorM2: 370000,
  },
  premium: {
    id: "premium",
    nombre: "Diseño Premium Llave en Mano",
    descripcion: "Vivienda contemporánea con terminaciones superiores y arquitectura de autor.",
    valorM2: 420000,
  },
  hormigon: {
    id: "hormigon",
    nombre: "Hormigón / Sólido",
    descripcion: "Construcción tradicional de máxima robustez, durabilidad y aislación acústica.",
    valorM2: 720000,
  },
};

/**
 * Catálogo de fundaciones (base estructural según tipo de suelo).
 */
export const FOUNDATION_OPTIONS: FoundationOption[] = [
  {
    id: "pilotes_madera",
    nombre: "Instalación en pilotes de madera impregnada",
    tipoCalculo: "mt2",
    valorPorM2: 60000,
    empresa: "Nogales Constructora",
  },
  {
    id: "radier_hormigon",
    nombre: "Radier de hormigón armado estándar",
    tipoCalculo: "mt2",
    valorPorM2: 95000,
    empresa: "Nogales Constructora",
  },
  {
    id: "radier_full_terminado",
    nombre: "Radier completo con piso cerámico llave en mano",
    tipoCalculo: "mt2",
    valorPorM2: 140000,
    empresa: "Nogales Constructora",
  },
];

/**
 * Catálogo de obras complementarias rurales portadas de `extras.js`.
 */
export const ADDITIONAL_WORKS: AdditionalWorkItem[] = [
  // --- Terminaciones e Instalaciones Interiores (base: casa_m2 y artefactos) ---
  {
    // P1-05: id fiel al legacy (frontend-v2/extras.js usa "Instalacion_electrica",
    // con mayúscula inicial) — no "instalacion_electrica".
    id: "Instalacion_electrica",
    nombre: "Instalación eléctrica interior con materiales",
    tipoCalculo: "mt2",
    base: "casa_m2",
    category: "terminaciones",
    valorUnitario: 15000,
    defaultQty: 1,
    minQty: 1,
    maxQty: 1,
    descripcion: "Red eléctrica interior, interruptores, enchufes y tablero normalizado según m² de vivienda.",
  },
  {
    // P1-05: id fiel al legacy (frontend-v2/extras.js usa "piso ceramico",
    // con espacio, no guion bajo).
    id: "piso ceramico",
    nombre: "Instalación piso cerámico o flotante con materiales",
    tipoCalculo: "mt2",
    base: "casa_m2",
    category: "terminaciones",
    valorUnitario: 32000,
    defaultQty: 1,
    minQty: 1,
    maxQty: 1,
    descripcion: "Piso cerámico o flotante de alto tráfico instalado según m² de la vivienda elegida.",
  },
  {
    id: "pintura",
    nombre: "Servicio de pintura interior y exterior con materiales",
    tipoCalculo: "mt2",
    base: "casa_m2",
    category: "terminaciones",
    valorUnitario: 15000,
    defaultQty: 1,
    minQty: 1,
    maxQty: 1,
    descripcion: "Tratamiento completo de muros con sellador e impermeabilizante para clima rural.",
  },
  {
    id: "instalacion_sanitaria",
    nombre: "Instalación sanitaria interior con materiales",
    tipoCalculo: "mt2",
    base: "casa_m2",
    category: "terminaciones",
    valorUnitario: 18000,
    defaultQty: 1,
    minQty: 1,
    maxQty: 1,
    descripcion: "Red de agua fría y caliente, desagües y fitting según superficie de la vivienda.",
  },
  {
    id: "artefactos_cocina",
    nombre: "Kit de artefactos y grifería de cocina",
    tipoCalculo: "unidad",
    base: "manual",
    category: "terminaciones",
    valorUnitario: 850000,
    defaultQty: 1,
    minQty: 1,
    maxQty: 1, // P1-05: el legacy declara maxQty:1 para artefactos_cocina, no 2.
    descripcion: "Lavaplatos de acero inoxidable, grifería monomando y mueble base referencial.",
  },
  {
    id: "artefactos_bano",
    nombre: "Kit de artefactos sanitarios de baño",
    tipoCalculo: "unidad",
    base: "manual",
    category: "terminaciones",
    valorUnitario: 750000,
    defaultQty: 1,
    minQty: 1,
    maxQty: 3, // P1-05: el legacy declara maxQty:3 para artefactos_bano, no 4.
    descripcion: "WC ecológico, vanitorio con mueble, espejo y receptáculo con grifería completa.",
  },

  // --- Servicios Básicos e Habilitación de Terreno ---
  {
    id: "pozo_profundo",
    nombre: "Pozo profundo de agua potable (según metros)",
    tipoCalculo: "metro",
    base: "manual",
    category: "servicios",
    valorUnitario: 50000,
    defaultQty: 30,
    minQty: 10,
    maxQty: 100,
    descripcion: "Perforación y entubado de pozo para obtención de agua subterránea (base estimada 30m).",
  },
  {
    id: "fosa_septica",
    nombre: "Fosa séptica con kit de drenaje e instalación",
    tipoCalculo: "unidad",
    base: "manual",
    category: "servicios",
    valorUnitario: 1500000,
    defaultQty: 1,
    minQty: 1,
    maxQty: 5, // P1-05: el legacy declara maxQty:5 para fosa_septica, no 3.
    descripcion: "Sistema de tratamiento biológico de aguas servidas con cámara desgrasadora y kit de drenes.",
  },
  {
    id: "empalme_electrico",
    nombre: "Empalme eléctrico / acometida a la red",
    tipoCalculo: "unidad",
    base: "manual",
    category: "servicios",
    valorUnitario: 1500000,
    defaultQty: 1,
    minQty: 1,
    maxQty: 3,
    descripcion: "Poste de acometida, caja de medidor y tramitación técnica ante la compañía distribuidora.",
  },
  {
    id: "cierre_perimetral",
    nombre: "Cierre perimetral con polines y alambre de púas",
    tipoCalculo: "metro",
    base: "parcela_perimetro",
    category: "servicios",
    valorUnitario: 2000,
    defaultQty: 100,
    minQty: 20,
    maxQty: 500, // P1-05: el legacy declara maxQty:500 para cierre_perimetral, no 600.
    descripcion: "Cerco tradicional de campo con polines de pino impregnado y 4 hebras según perímetro.",
  },
  {
    // P1-05: id fiel al legacy (frontend-v2/extras.js usa "porton", no
    // "porton_acceso") — CotizadorWizard.tsx ya asume este id en su estado inicial.
    id: "porton",
    nombre: "Portón de acceso vehicular rústico",
    tipoCalculo: "unidad",
    base: "manual",
    category: "servicios",
    valorUnitario: 1200000,
    defaultQty: 1,
    minQty: 1,
    maxQty: 3,
    descripcion: "Portón de doble hoja en madera impregnada y fierro para entrada principal a la parcela.",
  },
  {
    id: "maquinaria",
    nombre: "Horas de maquinaria retroexcavadora",
    tipoCalculo: "hora",
    base: "manual",
    category: "servicios",
    valorUnitario: 42000,
    defaultQty: 10,
    minQty: 1,
    maxQty: 100,
    descripcion: "Nivelación de terraza de construcción, despeje de huella vehicular y zanjas.",
  },

  // --- Obras Exteriores & Amenidades ---
  {
    id: "piscina",
    nombre: "Piscina construida y equipada",
    tipoCalculo: "mt2",
    base: "manual",
    category: "amenidades",
    valorUnitario: 200000,
    defaultQty: 18,
    minQty: 6,
    maxQty: 50,
    descripcion: "Piscina de hormigón o fibra con bomba, filtro, caseta y luces LED (base referencial 18 m²).",
  },
  {
    id: "quincho",
    nombre: "Quincho campestre techado",
    tipoCalculo: "mt2",
    base: "manual",
    category: "amenidades",
    valorUnitario: 250000,
    defaultQty: 12,
    minQty: 4,
    maxQty: 30, // P1-05: el legacy declara maxQty:30 para quincho, no 40.
    descripcion: "Quincho de asados en madera y vigas a la vista con mesón, lavacopas y parrilla techada.",
  },
  {
    id: "terraza",
    nombre: "Terraza exterior en madera impregnada",
    tipoCalculo: "mt2",
    base: "manual",
    category: "amenidades",
    valorUnitario: 200000,
    defaultQty: 15,
    minQty: 5,
    maxQty: 60,
    descripcion: "Deck de madera impregnada sobre pilotes para disfrutar la vista del entorno natural.",
  },
];
