const STORAGE='tpl_crm_v2_records';
const groups=[
 ['Inicio',[['inicio','Inicio'],['analisis-global','Análisis Global']]],
 ['Personas',[['clientes','Clientes'],['propietarios','Propietarios'],['corredores','Corredores'],['partners','Partners']]],
 ['Operación',[['parcelas','Parcelas'],['proyectos','Proyectos'],['negociaciones','Negociaciones'],['visitas','Visitas y reservas'],['agenda','Agenda']]],
 ['Servicios',[['business','TPL Business'],['studio','TPL Studio Mark II'],['oficina','Oficina TPL']]],
 ['Control',[['tasaciones','Tasaciones'],['reportes','Reportes'],['administracion','Administración']]]
];
const demo={
 propietarios:[{id:'p1',nombre:'María González',correo:'maria@example.cl',telefono:'+56 9 5555 1111',comuna:'Quillón',onboarding:'Correo de acceso enviado',business:'No ha ingresado',proxima:'Enviar correo 2',parcelas:2},{id:'p2',nombre:'Carlos Fuentes',correo:'carlos@example.cl',telefono:'+56 9 5555 2222',comuna:'Florida',onboarding:'Perfil completo',business:'Activo',proxima:'Revisar precio',parcelas:1}],
 clientes:[{id:'c1',nombre:'Ana Muñoz',comuna:'Concepción',interes:'Parcela + casa',proyecto:'Fase 2/7',proxima:'Visita viernes'}],
 corredores:[{id:'r1',nombre:'Patricia Soto',comuna:'Biobío',propietarios:8,parcelas:14,proyectos:5}],
 partners:[{id:'pa1',nombre:'Construcciones del Sur',servicio:'Casas y radieres',estado:'Activo',proyectos:'2 activos'}],
 parcelas:[{id:'l1',nombre:'Los Aromos',comuna:'Florida',propietario:'Carlos Fuentes',estado:'Publicada',proyecto:'Fase 2/7',visitas:4},{id:'l2',nombre:'Santa Ana',comuna:'Quillón',propietario:'María González',estado:'En revisión',proyecto:'Sin proyecto',visitas:0},{id:'l3',nombre:'El Roble',comuna:'Quillón',propietario:'María González',estado:'Publicada',proyecto:'Fase 5/7',visitas:7}],
 proyectos:[
  {id:'TPL-0148',nombre:'Proyecto Los Aromos',cliente:'Ana Muñoz',parcela:'Los Aromos',fase:2,estado:'Activo',proxima:'Confirmar visita',avance:34,riesgo:'Medio',bloqueo:'Confirmación del propietario',actores:[{rol:'Compradora',nombre:'Ana Muñoz',estado:'al_dia',proxima:'Confirmar horario de visita',icono:'👤'},{rol:'Propietario',nombre:'Carlos Fuentes',estado:'bloquea',proxima:'Responder disponibilidad',icono:'🏡'},{rol:'Corredora',nombre:'Patricia Soto',estado:'esperando',proxima:'Coordinar a ambas partes',icono:'👩‍💼'},{rol:'Partner',nombre:'Construcciones del Sur',estado:'pendiente',proxima:'Preparar estimación de radier',icono:'🤝'}],eventos:[{fecha:'15 jul · 09:10',titulo:'Propiedad publicada',actor:'Carlos Fuentes',tipo:'propiedad.publicada'},{fecha:'18 jul · 12:30',titulo:'Compradora interesada',actor:'Ana Muñoz',tipo:'interes.registrado'},{fecha:'20 jul · 16:00',titulo:'Visita solicitada',actor:'Ana Muñoz',tipo:'visita.solicitada'},{fecha:'Hoy · 09:00',titulo:'Confirmación pendiente',actor:'Carlos Fuentes',tipo:'alerta.generada'}]},
  {id:'TPL-0132',nombre:'Proyecto El Roble',cliente:'Diego Reyes',parcela:'El Roble',fase:5,estado:'Activo',proxima:'Aprobar cotización',avance:71,riesgo:'Bajo',bloqueo:'Sin bloqueo crítico',actores:[{rol:'Comprador',nombre:'Diego Reyes',estado:'al_dia',proxima:'Aprobar cotización',icono:'👤'},{rol:'Propietaria',nombre:'María González',estado:'al_dia',proxima:'Esperar documentación',icono:'🏡'},{rol:'Constructora',nombre:'Casas del Biobío',estado:'esperando',proxima:'Esperar aprobación',icono:'🏗️'},{rol:'Partner de riego',nombre:'Riego Sur',estado:'pendiente',proxima:'Cotizar instalación',icono:'💧'}],eventos:[{fecha:'2 jul · 10:00',titulo:'Proyecto creado',actor:'Sistema TPL',tipo:'proyecto.creado'},{fecha:'8 jul · 15:20',titulo:'Oferta aceptada',actor:'María González',tipo:'oferta.aceptada'},{fecha:'14 jul · 11:45',titulo:'Diseño de casa elegido',actor:'Diego Reyes',tipo:'casa.seleccionada'},{fecha:'Hoy · 08:40',titulo:'Cotización lista para aprobar',actor:'Casas del Biobío',tipo:'cotizacion.lista'}]}
 ],
 negociaciones:[{id:'N-22',parcela:'Los Aromos',cliente:'Ana Muñoz',solicitud:'Portón incluido',estado:'Pendiente propietario',fecha:'Hoy'}],
 visitas:[{id:'V-8',parcela:'Los Aromos',cliente:'Ana Muñoz',fecha:'31 jul · 11:00',estado:'Confirmar'}],
 studio:[{cliente:'Construcciones del Sur',plan:'Servicio activo',estado:'Edición',avance:65,proyecto:'Video presentación'}],
 business:[{cliente:'María González',modalidad:'Sin definir',estado:'No ha ingresado',servicios:'Publicación'},{cliente:'Carlos Fuentes',modalidad:'Autogestión',estado:'Activo',servicios:'Estadísticas, visitas'}]
};
let custom=JSON.parse(localStorage.getItem(STORAGE)||'[]');
let current='inicio';
const nav=document.querySelector('#nav'),content=document.querySelector('#content'),title=document.querySelector('#viewTitle');
nav.innerHTML=groups.map(([g,items])=>`<div class="nav-group"><div class="nav-label">${g}</div>${items.map(([id,l])=>`<button class="nav-btn" data-view="${id}">${l}</button>`).join('')}</div>`).join('');
document.querySelector('#today').textContent=new Intl.DateTimeFormat('es-CL',{dateStyle:'medium'}).format(new Date());
function all(type){return [...(demo[type]||[]),...custom.filter(x=>x.tipo===type.slice(0,-1)||x.tipo===type)]}
function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function pill(s){let c=/activo|completo|publicada|acept|bajo|al día/i.test(s)?'ok':/bloque|alto|venc/i.test(s)?'danger':/pendiente|no ha|revisión|confirmar|medio|esperando/i.test(s)?'warn':'';return `<span class="pill ${c}">${esc(s||'Sin definir')}</span>`}
function dashboard(){return `<div class="hero"><div><h2>Buenos días</h2><p>Estas son las acciones que requieren atención hoy.</p></div><div class="score"><span><b>${all('propietarios').length}</b>Propietarios</span><span><b>${all('parcelas').length}</b>Parcelas</span><span><b>${all('proyectos').length}</b>Proyectos</span></div></div><div class="grid"><article class="card span4"><h3>Próximas acciones</h3><div class="list">${all('propietarios').map(x=>`<div class="item"><div class="item-main"><strong>${esc(x.nombre)}</strong><small class="muted">${esc(x.proxima||'Revisar ficha')}</small></div>${pill(x.business)}</div>`).join('')}</div></article><article class="card span4"><h3>Visitas y reservas</h3><div class="list">${all('visitas').map(x=>`<div class="item"><div class="item-main"><strong>${esc(x.parcela)}</strong><small>${esc(x.cliente)} · ${esc(x.fecha)}</small></div>${pill(x.estado)}</div>`).join('')}</div></article><article class="card span4"><h3>Negociaciones</h3><div class="list">${all('negociaciones').map(x=>`<div class="item"><div class="item-main"><strong>${esc(x.parcela)}</strong><small>${esc(x.solicitud)}</small></div>${pill(x.estado)}</div>`).join('')}</div></article><article class="card span8"><h3>Proyectos vivos</h3><div class="list">${all('proyectos').map(x=>`<button class="project-list-item" data-project="${esc(x.id)}"><div class="item-main"><strong>${esc(x.id)} · ${esc(x.nombre)}</strong><small>${esc(x.cliente)} · ${esc(x.parcela)}</small><div class="progress"><i style="width:${x.avance||Math.round((x.fase||0)/7*100)}%"></i></div></div>${pill(`Fase ${x.fase}/7`)}</button>`).join('')}</div></article><article class="card span4"><h3>Análisis Global</h3><div class="analysis-mini"><strong>1 bloqueo crítico</strong><small>El proyecto Los Aromos espera confirmación del propietario.</small><button class="primary" data-view="analisis-global">Abrir análisis</button></div></article></div>`}
function globalAnalysis(){const projects=all('proyectos');const atRisk=projects.filter(p=>/alto|medio/i.test(p.riesgo||'')).length;const blockers=projects.filter(p=>p.bloqueo&&!/sin bloqueo/i.test(p.bloqueo)).length;return `<div class="global-head"><div><small>Centro de inteligencia operativo</small><h2>ANÁLISIS GLOBAL</h2><p>Observa proyectos, actores, eventos, riesgos y próximas acciones desde una sola vista.</p></div><button class="primary" data-view="proyectos">Ver proyectos</button></div><div class="metric-grid"><article class="metric"><span>Proyectos activos</span><strong>${projects.length}</strong><small>${projects.filter(p=>p.estado==='Activo').length} en ejecución</small></article><article class="metric"><span>Actores conectados</span><strong>${projects.reduce((n,p)=>n+(p.actores?.length||0),0)}</strong><small>En proyectos vigentes</small></article><article class="metric"><span>Bloqueos</span><strong>${blockers}</strong><small>Requieren seguimiento</small></article><article class="metric"><span>Riesgo medio/alto</span><strong>${atRisk}</strong><small>Prioridad operativa</small></article></div><div class="grid"><article class="card span8"><div class="section-title"><div><h3>Radar de proyectos</h3><p class="muted">Ordenado por necesidad de intervención.</p></div></div><div class="project-radar">${projects.map(p=>`<button class="radar-row" data-project="${esc(p.id)}"><div><strong>${esc(p.nombre)}</strong><small>${esc(p.id)} · ${esc(p.cliente)} · ${esc(p.parcela)}</small></div><div class="radar-progress"><span style="width:${p.avance||0}%"></span></div><b>${p.avance||0}%</b>${pill(p.riesgo||'Sin evaluar')}</button>`).join('')}</div></article><article class="card span4"><h3>Alertas inteligentes</h3><div class="alert-stack"><article class="alert alert-critical"><strong>Proyecto bloqueado</strong><small>Los Aromos espera respuesta del propietario.</small></article><article class="alert"><strong>Oportunidad comercial</strong><small>Dos compradores buscan parcelas con agua en Florida.</small></article><article class="alert"><strong>Partner disponible</strong><small>Construcciones del Sur tiene capacidad esta semana.</small></article></div></article><article class="card span6"><h3>Actividad reciente</h3><div class="timeline compact">${projects.flatMap(p=>(p.eventos||[]).slice(-2).map(e=>({...e,project:p.id}))).slice(0,6).map(e=>`<article><strong>${esc(e.titulo)}</strong><small>${esc(e.actor)} · ${esc(e.project)} · ${esc(e.fecha)}</small></article>`).join('')}</div></article><article class="card span6"><h3>Recomendación de Análisis Global</h3><div class="recommendation"><span>🧠</span><div><strong>Priorizar confirmación de visita</strong><p>Contactar hoy a Carlos Fuentes. Su respuesta desbloquea la visita de Ana Muñoz y evita que el proyecto pierda ritmo.</p><button class="primary" data-project="TPL-0148">Abrir proyecto</button></div></div></article></div>`}
function project360(p){if(!p)return `<div class="empty">Proyecto no encontrado.</div>`;return `<div class="project-head"><button class="back-link" data-view="proyectos">← Volver a proyectos</button><div class="project-title-row"><div><small>${esc(p.id)}</small><h2>${esc(p.nombre)}</h2><p>${esc(p.parcela)} · Cliente: ${esc(p.cliente)}</p></div><div class="project-health"><b>${p.avance||0}%</b><span>Avance general</span>${pill(`Riesgo ${p.riesgo||'sin evaluar'}`)}</div></div></div><div class="project-summary"><article><span>Fase actual</span><strong>${p.fase}/7</strong></article><article><span>Próxima acción</span><strong>${esc(p.proxima)}</strong></article><article><span>Bloqueo</span><strong>${esc(p.bloqueo)}</strong></article><article><span>Estado</span>${pill(p.estado)}</article></div><div class="card project-network-card"><div class="section-title"><div><h3>Actores del proyecto</h3><p class="muted">Cada actor muestra su estado y siguiente responsabilidad.</p></div></div><div class="actor-network"><div class="project-core"><span>📁</span><strong>${esc(p.id)}</strong><small>Proyecto central</small></div><div class="actor-grid">${(p.actores||[]).map((a,i)=>`<button class="actor-node state-${esc(a.estado)}" data-actor="${i}"><span class="actor-icon">${a.icono||'👤'}</span><strong>${esc(a.nombre)}</strong><small>${esc(a.rol)}</small><em>${actorStateLabel(a.estado)}</em><span>${esc(a.proxima)}</span></button>`).join('')}</div></div></div><div class="grid"><article class="card span7"><h3>Línea de tiempo del proyecto</h3><div class="project-timeline">${(p.eventos||[]).map(e=>`<article><time>${esc(e.fecha)}</time><div><strong>${esc(e.titulo)}</strong><small>${esc(e.actor)} · ${esc(e.tipo)}</small></div></article>`).join('')}</div></article><article class="card span5"><h3>Lectura inteligente</h3><div class="recommendation vertical"><span>🧠</span><div><strong>${/sin bloqueo/i.test(p.bloqueo)?'Proyecto saludable':'Intervención recomendada'}</strong><p>${/sin bloqueo/i.test(p.bloqueo)?'No existen bloqueos críticos. Mantener seguimiento de la próxima acción.':`Resolver “${esc(p.bloqueo)}” antes de avanzar a la siguiente fase.`}</p></div></div><h3 class="subheading">Responsables próximos</h3><div class="list">${(p.actores||[]).filter(a=>a.estado!=='al_dia').map(a=>`<div class="item"><div class="item-main"><strong>${esc(a.nombre)}</strong><small>${esc(a.proxima)}</small></div>${pill(actorStateLabel(a.estado))}</div>`).join('')||'<p class="muted">Todos los actores están al día.</p>'}</div></article></div>`}
function actorStateLabel(s){return ({al_dia:'Al día',pendiente:'Pendiente',esperando:'Esperando respuesta',bloquea:'Bloquea proyecto'})[s]||s||'Sin estado'}
function tableView(type,columns){const rows=all(type);return `<div class="toolbar"><input id="search" placeholder="Buscar..."><select id="filter"><option value="">Todos los estados</option><option>Activo</option><option>Pendiente</option><option>Sin proyecto</option></select></div><div class="table-wrap"><table><thead><tr>${columns.map(c=>`<th>${c[1]}</th>`).join('')}<th>Acción</th></tr></thead><tbody id="tbody">${rows.map(r=>row(r,columns,type)).join('')}</tbody></table></div>`}
function row(r,columns,type){return `<tr>${columns.map(([k])=>`<td>${k==='estado'||k==='business'||k==='proyecto'?pill(r[k]):esc(r[k]??'—')}</td>`).join('')}<td>${type==='proyectos'?`<button class="primary small" data-project="${esc(r.id)}">Vista 360°</button>`:`<button class="nav-btn detail-btn" data-detail='${JSON.stringify(r).replaceAll("'","&#39;")}'>Ver ficha</button>`}</td></tr>`}
function office(){return `<div class="grid"><article class="card span6"><h3>Campañas</h3><p class="muted">Selecciona una audiencia por tipo, comuna, estado o actividad.</p><div class="list"><div class="item"><div class="item-main"><strong>Propietarios de Quillón</strong><small>Ajuste de precios · 18 destinatarios</small></div>${pill('Borrador')}</div><div class="item"><div class="item-main"><strong>Sin ingreso a TPL Business</strong><small>Correo 2 · 6 destinatarios</small></div>${pill('Preparar')}</div></div><button class="primary">Crear campaña</button></article><article class="card span6"><h3>Automatizaciones</h3><div class="timeline"><article><strong>Día 0 · Bienvenida</strong><small>Correo + acceso a TPL Business</small></article><article><strong>Día 3 · Sin ingreso</strong><small>Recordatorio 1</small></article><article><strong>Día 7 · Sin ingreso</strong><small>Recordatorio 2</small></article><article><strong>Día 10 · Sin ingreso</strong><small>Crear tarea de llamada</small></article></div></article><article class="card span12"><h3>Conexión con Análisis Global</h3><div class="item"><div class="item-main"><strong>Los eventos activarán flujos y alertas</strong><small>La siguiente etapa conectará plantillas, esperas, condiciones y ejecuciones reales.</small></div><button class="primary" data-view="analisis-global">Abrir Análisis Global</button></div></article></div>`}
const cols={clientes:[['nombre','Cliente'],['comuna','Comuna'],['interes','Interés'],['proyecto','Proyecto'],['proxima','Próxima acción']],propietarios:[['nombre','Propietario'],['comuna','Comuna'],['onboarding','Incorporación'],['business','TPL Business'],['parcelas','Parcelas'],['proxima','Próxima acción']],corredores:[['nombre','Corredor'],['comuna','Zona'],['propietarios','Propietarios'],['parcelas','Parcelas'],['proyectos','Proyectos']],partners:[['nombre','Partner'],['servicio','Servicio'],['estado','Estado'],['proyectos','Proyectos']],parcelas:[['nombre','Parcela'],['comuna','Comuna'],['propietario','Propietario'],['estado','Estado'],['proyecto','Proyecto'],['visitas','Visitas']],proyectos:[['id','ID'],['nombre','Proyecto'],['cliente','Cliente'],['parcela','Parcela'],['fase','Fase'],['estado','Estado'],['proxima','Próxima acción']],negociaciones:[['id','ID'],['parcela','Parcela'],['cliente','Cliente'],['solicitud','Solicitud'],['estado','Estado'],['fecha','Fecha']],visitas:[['id','ID'],['parcela','Parcela'],['cliente','Cliente'],['fecha','Fecha'],['estado','Estado']],business:[['cliente','Cliente'],['modalidad','Modalidad'],['estado','Estado'],['servicios','Servicios']],studio:[['cliente','Cliente'],['plan','Servicio'],['estado','Estado'],['avance','Avance %'],['proyecto','Producción']]};
function render(view){current=view;document.querySelectorAll('.nav-btn[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));let label=[...groups.flatMap(g=>g[1])].find(x=>x[0]===view)?.[1]||view;title.textContent=label;if(view==='inicio')content.innerHTML=dashboard();else if(view==='analisis-global')content.innerHTML=globalAnalysis();else if(view==='oficina')content.innerHTML=office();else if(view==='studio')content.innerHTML=`<div class="grid"><article class="card span8"><h3>TPL Studio Mark II</h3><p class="muted">Asesor transversal de imagen, comunicación, Landing, contenido y campañas. Consume la ficha maestra del CRM y devuelve borradores y aprobaciones.</p><a class="primary" href="../tpl-business/studio-mark-ii/index.html">Abrir Studio Mark II</a></article><article class="card span4"><h3>Regla de seguridad</h3><p class="muted">Nada se publica ni gasta presupuesto sin aprobación explícita.</p></article></div>`;else if(view.startsWith('proyecto:')){const id=view.split(':').slice(1).join(':');title.textContent='Vista 360° del Proyecto';content.innerHTML=project360(all('proyectos').find(p=>p.id===id));}else if(cols[view])content.innerHTML=tableView(view,cols[view]);else content.innerHTML=`<div class="card"><h3>${esc(label)}</h3><p class="muted">Módulo preparado para conectarse con Supabase. Mantendrá una única fuente de datos y bitácora.</p></div>`;window.scrollTo({top:0,behavior:'smooth'});}
nav.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){render(b.dataset.view);document.querySelector('.sidebar').classList.remove('open')}});
document.querySelector('#menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
document.querySelector('#quickAdd').onclick=()=>document.querySelector('#recordDialog').showModal();
document.querySelector('#saveRecord').onclick=e=>{e.preventDefault();const x={id:crypto.randomUUID(),tipo:recordType.value,nombre:recordName.value,correo:recordEmail.value,telefono:recordPhone.value,comuna:recordCommune.value,notas:recordNotes.value,creado:new Date().toISOString()};custom.push(x);localStorage.setItem(STORAGE,JSON.stringify(custom));recordForm.reset();recordDialog.close();render(current)};
content.addEventListener('click',e=>{const project=e.target.closest('[data-project]');if(project){render(`proyecto:${project.dataset.project}`);return}const go=e.target.closest('[data-view]');if(go){render(go.dataset.view);return}const detail=e.target.closest('[data-detail]');if(detail){const r=JSON.parse(detail.dataset.detail);alert(Object.entries(r).map(([k,v])=>`${k}: ${v}`).join('\n'))}});
render('inicio');
window.addEventListener('DOMContentLoaded',async()=>{if(!window.TPLDataService)return;try{const properties=await window.TPLDataService.listPublishedProperties();const events=await window.TPLDataService.listEvents();window.TPLCRMCanonical={properties,events,source:window.TPLDataService.hasBackend()?'supabase':'local'};const badge=document.createElement('div');badge.className='canonical-status';badge.textContent=`Núcleo canónico: ${properties.length} propiedades · ${events.length} eventos · ${window.TPLCRMCanonical.source}`;document.querySelector('.topbar')?.appendChild(badge)}catch(error){console.warn('CRM V2: no fue posible sincronizar núcleo canónico',error)}});
