import { createClient } from 'npm:@supabase/supabase-js@2';
import { corsHeaders, jsonResponse } from '../_shared/cors.ts';
import { consumeRateLimit, publicError, readJson, UUID_RE } from '../_shared/security.ts';
const safe=(v:unknown,n=240)=>String(v??'').replace(/[\r\n<>]/g,' ').trim().slice(0,n);
async function mail(apiKey:string,from:string,replyTo:string,to:string,subject:string,html:string,key:string){const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({from,to:[to],reply_to:replyTo,subject,html})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`Resend: ${p?.message||r.statusText}`);return p;}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders(req)});if(req.method!=='POST')return jsonResponse(req, {ok:false,error:'Método no permitido'},405);
 const url=Deno.env.get('SUPABASE_URL'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),resend=Deno.env.get('RESEND_API_KEY');const site=(Deno.env.get('TPL_SITE_URL')||'https://www.parcelalista.cl').replace(/\/$/,'');const from=Deno.env.get('TPL_PARTNER_EMAIL_FROM')||'Tu Parcela Lista <partners@parcelalista.cl>';const reply=Deno.env.get('TPL_REPLY_TO')||'tuparcelalista@gmail.com';if(!url||!service||!resend)return jsonResponse(req, {ok:false,error:'Configuración incompleta'},500);
 const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});let onboardingId:string|null=null;
 try{await consumeRateLimit(admin,req,'activar-partner',10,300);const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!token)throw new Error('Sesión requerida');const {data:{user}}=await admin.auth.getUser(token);if(!user)throw new Error('Sesión inválida');const {data:staff}=await admin.from('tpl_staff').select('user_id').eq('user_id',user.id).maybeSingle();if(!staff)throw new Error('NO_AUTORIZADO');
  const body=await readJson(req,16000);const postId=safe(body.postulacion_id,80);if(!UUID_RE.test(postId))throw new Error('POSTULACION_INVALIDA');
  const {data:o,error:oe}=await admin.from('tpl_onboarding_partner').select('*,tpl_partner_postulaciones(*),tpl_partner_perfiles(*)').eq('postulacion_id',postId).single();if(oe||!o)throw new Error('Onboarding Partner no encontrado');onboardingId=o.id;if(o.estado==='completado')return jsonResponse(req, {ok:true,already_completed:true});
  await admin.from('tpl_onboarding_partner').update({estado:'procesando',intentos:Number(o.intentos||0)+1,ultimo_error:null,updated_at:new Date().toISOString()}).eq('id',o.id);
  const p:any=o.tpl_partner_postulaciones,profile:any=o.tpl_partner_perfiles;const email=safe(o.email,250).toLowerCase();const redirect=`${site}/plataforma/tpl-business/`;let link='';let authId=o.auth_user_id;
  const inv=await admin.auth.admin.generateLink({type:'invite',email,options:{redirectTo:redirect,data:{nombre:p.nombre_responsable,actor_id:o.actor_id,rol:'partner'}}});if(!inv.error&&inv.data?.properties?.action_link){link=inv.data.properties.action_link;authId=inv.data.user?.id||authId;}else{const mg=await admin.auth.admin.generateLink({type:'magiclink',email,options:{redirectTo:redirect}});if(mg.error||!mg.data?.properties?.action_link)throw new Error(mg.error?.message||'No fue posible crear acceso');link=mg.data.properties.action_link;authId=mg.data.user?.id||authId;}
  const {data:plan}=await admin.from('tpl_planes_comerciales').select('*').eq('codigo','partner_basico').eq('activo',true).single();if(!plan)throw new Error('Plan Partner Básico no disponible');let subId=o.suscripcion_id;
  if(!subId){const {data:sub}=await admin.from('tpl_suscripciones').insert({actor_id:o.actor_id,plan_id:plan.id,estado:'prueba',inicio_at:new Date().toISOString(),prueba_hasta:new Date(Date.now()+30*86400000).toISOString(),metadata:{segmento:'partner',postulacion_id:postId}}).select('id').single();subId=sub?.id;}
  let campaignId=o.campaign_id;if(!campaignId){const {data:c}=await admin.from('studio_campaigns').insert({owner_user_id:authId||null,nombre:`Landing · ${p.nombre_comercial}`,tipo_objetivo:'partner',objetivo_id:o.actor_id,objetivo_comercial:'captar_solicitudes',tono:'profesional y cercano',audiencia:`Clientes rurales en ${p.region||'Chile'}`,estado:'borrador',datos_fuente:{partner_actor_id:o.actor_id,perfil_id:o.perfil_id,slug:profile?.slug},estrategia:{propuesta_corta:p.propuesta_corta,diferenciacion:p.diferenciacion,servicios:p.especialidades,etapas:p.etapas_servicio},metadata:{origen:'onboarding_partner',trial:true}}).select('id').single();campaignId=c?.id;}
  const name=safe(p.nombre_responsable||'Partner'),business=safe(p.nombre_comercial||'tu empresa');
  await mail(resend,from,reply,email,`¡${business} fue aprobado en Red Partner!`,`<div style="font-family:Arial;max-width:620px;margin:auto;color:#17324d"><h2>Hola ${name}, tu empresa fue aprobada</h2><p><strong>${business}</strong> ya forma parte de Red Partner TPL.</p><p>Activamos una prueba gratuita de <strong>30 días del Plan Partner Básico</strong>.</p><ul><li>Perfil público y puntuación</li><li>Landing comercial</li><li>CRM básico y solicitudes</li><li>Galería, cotizaciones y agenda</li><li>Acceso a TPL Studio</li></ul><p><a href="${link}" style="background:#f2b705;color:#17324d;padding:13px 18px;border-radius:8px;text-decoration:none;font-weight:bold">Activar mi cuenta Partner</a></p></div>`,`tpl-partner-aprobado-${postId}`);
  await mail(resend,from,reply,email,'Tu TPL Business Partner ya está disponible',`<div style="font-family:Arial;max-width:620px;margin:auto;color:#17324d"><h2>Tu espacio comercial está preparado</h2><p>Al ingresar podrás completar tu perfil, revisar tu puntuación, editar la landing y administrar futuras solicitudes.</p><p><a href="${link}" style="background:#073a5a;color:white;padding:13px 18px;border-radius:8px;text-decoration:none">Entrar a TPL Business</a></p><p>La prueba vence en 30 días. Tus datos no se eliminarán si decides no continuar.</p></div>`,`tpl-partner-acceso-${postId}`);
  await admin.from('tpl_onboarding_partner').update({auth_user_id:authId,suscripcion_id:subId,campaign_id:campaignId,estado:'completado',correo_aprobacion_estado:'enviado',correo_acceso_estado:'enviado',completado_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',o.id);
  return jsonResponse(req, {ok:true,estado:'completado',actor_id:o.actor_id,perfil_id:o.perfil_id,suscripcion_id:subId,campaign_id:campaignId,portal_url:redirect});
 }catch(e){const msg=e instanceof Error?e.message:'Error de activación';if(onboardingId)await admin.from('tpl_onboarding_partner').update({estado:'error',ultimo_error:msg.slice(0,1000),updated_at:new Date().toISOString()}).eq('id',onboardingId);return jsonResponse(req, {ok:false,error:publicError(e)},400);}});
