const fs = require('fs');
const files = ['frontend-v2/parcela.html', 'frontend-v2/parcela-v2.html', 'frontend-v2/js/parcela.js', 'frontend-v2/js/index.js'];
files.forEach(f => {
    let content = fs.readFileSync(f, 'utf8');
    let safeFixed = content
        .replace(/¿+Te imaginas/g, '¿Te imaginas')
        .replace(/aqu¿+/g, 'aquí')
        .replace(/¿+C¿+mo/g, '¿Cómo')
        .replace(/¿+Qu¿+/g, '¿Qué')
        .replace(/¿+Quieres/g, '¿Quieres')
        .replace(/¿+Puedo/g, '¿Puedo')
        .replace(/¿+La /g, '¿La ')
        .replace(/qu¿+ hay/g, 'qué hay')
        .replace(/D¿+nde est¿+/g, 'Dónde está')
        .replace(/¿+ndice/g, 'Índice')
        .replace(/condici¿+n/g, 'condición')
        .replace(/continǧa/g, 'continúa')
        .replace(/contin¿+a/g, 'continúa')
        .replace(/ubicaci¿+n/g, 'ubicación')
        .replace(/Ubicaci¿+n/g, 'Ubicación')
        .replace(/UBICACI¿+N/g, 'UBICACIÓN')
        .replace(/VALORACI¿+N/g, 'VALORACIÓN')
        .replace(/posici¿+n/g, 'posición')
        .replace(/Posici¿+n/g, 'Posición')
        .replace(/Tasaci¿+n/g, 'Tasación')
        .replace(/negociaci¿+n/g, 'negociación')
        .replace(/informaci¿+n/g, 'información')
        .replace(/Informaci¿+n/g, 'Información')
        .replace(/decisi¿+n/g, 'decisión')
        .replace(/visi¿+n/g, 'visión')
        .replace(/r¿+pida/g, 'rápida')
        .replace(/R¿+pida/g, 'Rápida')
        .replace(/M¿+x:/g, 'Máx:')
        .replace(/M¿+n:/g, 'Mín:')
        .replace(/m¿+s/g, 'más')
        .replace(/c¿+lculos/g, 'cálculos')
        .replace(/t¿+cnica/g, 'técnica')
        .replace(/T¿+tulos/g, 'Títulos')
        .replace(/t¿+tulos/g, 'títulos')
        .replace(/fotograf¿+a/g, 'fotografía')
        .replace(/estad¿+stica/g, 'estadística')
        .replace(/due¿+o/g, 'dueño')
        .replace(/ASESOR¿+A/g, 'ASESORÍA')
        .replace(/PR¿+XIMO/g, 'PRÓXIMO')
        .replace(/dise¿+o/g, 'diseño')
        .replace(/port¿+n/g, 'portón')
        .replace(/b¿+sica/g, 'básica')
        .replace(/despu¿+s/g, 'después')
        .replace(/acompa¿+arte/g, 'acompañarte')
        .replace(/revisi¿+n/g, 'revisión')
        .replace(/pr¿+ximos/g, 'próximos')
        .replace(/ayudar¿+a/g, 'ayudaría')
        .replace(/Tel¿+fono/g, 'Teléfono')
        .replace(/electr¿+nico/g, 'electrónico')
        .replace(/cotizaci¿+n/g, 'cotización')
        .replace(/Cotizaci¿+n/g, 'Cotización')
        .replace(/S¿+/g, 'Sí');
    fs.writeFileSync(f, safeFixed, 'utf8');
});
console.log('Fixed literal broken characters.');
