const fs = require('fs');
const files = ['frontend-v2/parcela.html', 'frontend-v2/parcela-v2.html', 'frontend-v2/js/parcela.js', 'frontend-v2/js/index.js'];
files.forEach(f => {
    let content = fs.readFileSync(f, 'utf8');
    let safeFixed = content
        .replace(/\ufffdTe imaginas/g, '¿Te imaginas')
        .replace(/\ufffdaqu\ufffd/g, 'aquí')
        .replace(/\ufffdaqu/g, 'aquí')
        .replace(/aqu\ufffd/g, 'aquí')
        .replace(/aquí\.\.\./g, 'aquí?')
        .replace(/\ufffdC\ufffdmo/g, '¿Cómo')
        .replace(/\ufffdQu\ufffd/g, '¿Qué')
        .replace(/\ufffdQuieres/g, '¿Quieres')
        .replace(/\ufffdPuedo/g, '¿Puedo')
        .replace(/\ufffdLa /g, '¿La ')
        .replace(/\ufffdqu\ufffd hay/g, 'qué hay')
        .replace(/qu\ufffd hay/g, 'qué hay')
        .replace(/D\ufffdnde est\ufffd/g, 'Dónde está')
        .replace(/\ufffdndice/g, 'Índice')
        .replace(/condici\ufffdn/g, 'condición')
        .replace(/contin\ufffda/g, 'continúa')
        .replace(/ubicaci\ufffdn/g, 'ubicación')
        .replace(/Ubicaci\ufffdn/g, 'Ubicación')
        .replace(/UBICACI\ufffdN/g, 'UBICACIÓN')
        .replace(/VALORACI\ufffdN/g, 'VALORACIÓN')
        .replace(/posici\ufffdn/g, 'posición')
        .replace(/Posici\ufffdn/g, 'Posición')
        .replace(/Tasaci\ufffdn/g, 'Tasación')
        .replace(/negociaci\ufffdn/g, 'negociación')
        .replace(/informaci\ufffdn/g, 'información')
        .replace(/Informaci\ufffdn/g, 'Información')
        .replace(/decisi\ufffdn/g, 'decisión')
        .replace(/visi\ufffdn/g, 'visión')
        .replace(/r\ufffdpida/g, 'rápida')
        .replace(/R\ufffdpida/g, 'Rápida')
        .replace(/M\ufffdx:/g, 'Máx:')
        .replace(/M\ufffdn:/g, 'Mín:')
        .replace(/m\ufffds/g, 'más')
        .replace(/c\ufffdlculos/g, 'cálculos')
        .replace(/t\ufffdcnica/g, 'técnica')
        .replace(/T\ufffdtulos/g, 'Títulos')
        .replace(/t\ufffdtulos/g, 'títulos')
        .replace(/fotograf\ufffda/g, 'fotografía')
        .replace(/estad\ufffdstica/g, 'estadística')
        .replace(/due\ufffdo/g, 'dueño')
        .replace(/ASESOR\ufffdA/g, 'ASESORÍA')
        .replace(/PR\ufffdXIMO/g, 'PRÓXIMO')
        .replace(/dise\ufffdo/g, 'diseño')
        .replace(/port\ufffdn/g, 'portón')
        .replace(/b\ufffdsica/g, 'básica')
        .replace(/despu\ufffds/g, 'después')
        .replace(/acompa\ufffdarte/g, 'acompañarte')
        .replace(/revisi\ufffdn/g, 'revisión')
        .replace(/pr\ufffdximos/g, 'próximos')
        .replace(/ayudar\ufffda/g, 'ayudaría')
        .replace(/Tel\ufffdfono/g, 'Teléfono')
        .replace(/electr\ufffdnico/g, 'electrónico')
        .replace(/cotizaci\ufffdn/g, 'cotización')
        .replace(/Cotizaci\ufffdn/g, 'Cotización')
        .replace(/S\ufffd/g, 'Sí');
    fs.writeFileSync(f, safeFixed, 'utf8');
});
console.log('Fixed U+FFFD characters.');
