-- TPL Tasador V2.3 — SQL para encolar recálculo masivo
-- Ejecutar en Supabase SQL Editor o via supabase db push
-- Fecha: 2026-08-10T02:49:11.126Z
-- Propiedades: 32

INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('6a749e24-b2a2-490b-896f-5347f8657fcb', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('55017df4-e557-4f9a-8c37-9dbf2fa4f796', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('e839fc10-5538-431e-9415-f900c5956cdf', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('dec71129-7d16-4bca-a1d8-bf508f4297fb', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('dd042326-25d0-452a-b222-2172162aa0a1', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('d17473c4-eef0-4757-a9bc-fec8229347b4', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('5833f5eb-2a52-4639-a7b4-2d2887b7681f', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('7576efac-7eb6-4049-8185-e148357e8bfd', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('86685702-d6b7-431a-883e-a614ef9a5e15', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('8ef15268-1ca3-48e0-8bc1-2969e1092553', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('023b9e7d-0561-4f95-a5f8-c2dae6c85f1c', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('1bbe3e83-f464-48b1-8689-1201b2082cda', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('14d670f4-70ca-4706-ab78-47a7c0f4a619', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('3638ed74-44ac-4337-8dde-6bef4adc3803', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('c4a50080-d99a-436a-a6a9-9700df30d708', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('2a32a70d-c7f8-4eb9-8f79-c8f76151f87f', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('86fc06ab-2a4c-427b-9d81-13db9d6177d7', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('f1410d68-a629-49e7-972e-bb45ce687946', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('c28641d2-3dc7-4ef0-9a75-d9c990de3354', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('3377f828-c9ed-4d54-a13b-4c0fd58c87cb', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('afb09c54-ec1f-4202-8379-3c5c5038ce3a', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('fd811fd7-4f7b-4279-8dcf-32b33346d75c', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('8118c042-975d-4933-8a2a-15ac053a3c34', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('78172e87-c1d1-4c94-b2b5-93ceafbf5fed', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('c981f721-21b8-48ab-9ad8-5e1fa7e64e86', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('093355bf-dd05-4579-a3ad-b4d3d6f5cf0e', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('268e05c1-4b71-45eb-9237-a4b0bef33e54', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('21e2e93f-d012-4183-9d7f-08213e289aa5', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('2cf624fd-4ead-42e4-af11-20227ddba2cb', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('6da1141a-0bbb-4f8e-907d-cf702a23c1e1', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('5b09f810-b16a-4576-a37d-25b2768359ee', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();
INSERT INTO tpl_cola_recalculo_tasacion (propiedad_id, estado, solicitado_por, motivo) VALUES ('9bc37c4c-8d8a-42fc-b412-395993cc1e4a', 'pendiente', 'recalculo_v23', 'Recálculo masivo V2.3') ON CONFLICT (propiedad_id) WHERE estado IN ('pendiente','procesando') DO UPDATE SET estado = 'pendiente', motivo = 'Recálculo masivo V2.3', updated_at = now();

-- Después de ejecutar, invocar el Edge Function:
-- POST https://hwyscirbycojwndyzozn.supabase.co/functions/v1/procesar-recalculo-tasador
-- Headers: x-tpl-internal-secret: <TPL_INTERNAL_FUNCTIONS_SECRET>
-- Body: { "limit": 50 }
